from werkzeug.security import generate_password_hash

from .database import SessionLocal, init_db
from .models import Impregnation, Material, User

MATERIALS = [{'kod': 'SCHOTT_N_BK7',
  'name': 'SCHOTT N-BK7',
  'group': 'стекло',
  'lambda_w_mk': 1.114,
  'density_kg_m3': 2510,
  'heat_capacity_j_kgk': 858,
  'expansion_1_k': 7.1e-06,
  'tg_c': 557,
  't_max_c': 180,
  'moisture_absorption_pct': 0.02,
  'heat_sensitivity': 0.25},
 {'kod': 'SCHOTT_N_F2',
  'name': 'SCHOTT N-F2',
  'group': 'стекло',
  'lambda_w_mk': 0.78,
  'density_kg_m3': 3610,
  'heat_capacity_j_kgk': 670,
  'expansion_1_k': 8.2e-06,
  'tg_c': 430,
  't_max_c': 150,
  'moisture_absorption_pct': 0.03,
  'heat_sensitivity': 0.35},
 {'kod': 'CORNING_7980',
  'name': 'Corning 7980',
  'group': 'кварц',
  'lambda_w_mk': 1.38,
  'density_kg_m3': 2200,
  'heat_capacity_j_kgk': 740,
  'expansion_1_k': 5.5e-07,
  'tg_c': 1100,
  't_max_c': 220,
  'moisture_absorption_pct': 0.01,
  'heat_sensitivity': 0.12},
 {'kod': 'PPG_CR39',
  'name': 'PPG CR-39',
  'group': 'полимер',
  'lambda_w_mk': 0.16,
  'density_kg_m3': 1310,
  'heat_capacity_j_kgk': 1090,
  'expansion_1_k': 6.2e-05,
  'tg_c': 85,
  't_max_c': 68,
  'moisture_absorption_pct': 0.25,
  'heat_sensitivity': 0.88},
 {'kod': 'PPG_TRIVEX',
  'name': 'PPG Trivex',
  'group': 'полимер',
  'lambda_w_mk': 0.19,
  'density_kg_m3': 1110,
  'heat_capacity_j_kgk': 1250,
  'expansion_1_k': 5.5e-05,
  'tg_c': 118,
  't_max_c': 82,
  'moisture_absorption_pct': 0.12,
  'heat_sensitivity': 0.72},
 {'kod': 'PC_OPT',
  'name': 'Оптический поликарбонат',
  'group': 'полимер',
  'lambda_w_mk': 0.2,
  'density_kg_m3': 1200,
  'heat_capacity_j_kgk': 1250,
  'expansion_1_k': 6.5e-05,
  'tg_c': 147,
  't_max_c': 92,
  'moisture_absorption_pct': 0.18,
  'heat_sensitivity': 0.74},
 {'kod': 'PMMA_OPT',
  'name': 'Оптический ПММА',
  'group': 'полимер',
  'lambda_w_mk': 0.19,
  'density_kg_m3': 1180,
  'heat_capacity_j_kgk': 1470,
  'expansion_1_k': 7e-05,
  'tg_c': 105,
  't_max_c': 78,
  'moisture_absorption_pct': 0.3,
  'heat_sensitivity': 0.82},
 {'kod': 'MITSUI_MR8',
  'name': 'Mitsui MR-8',
  'group': 'полимер',
  'lambda_w_mk': 0.17,
  'density_kg_m3': 1300,
  'heat_capacity_j_kgk': 1180,
  'expansion_1_k': 5.8e-05,
  'tg_c': 118,
  't_max_c': 84,
  'moisture_absorption_pct': 0.12,
  'heat_sensitivity': 0.7},
 {'kod': 'MITSUI_MR10',
  'name': 'Mitsui MR-10',
  'group': 'полимер',
  'lambda_w_mk': 0.17,
  'density_kg_m3': 1360,
  'heat_capacity_j_kgk': 1160,
  'expansion_1_k': 5.5e-05,
  'tg_c': 100,
  't_max_c': 78,
  'moisture_absorption_pct': 0.12,
  'heat_sensitivity': 0.76},
 {'kod': 'MITSUI_MR174',
  'name': 'Mitsui MR-174',
  'group': 'полимер',
  'lambda_w_mk': 0.16,
  'density_kg_m3': 1470,
  'heat_capacity_j_kgk': 1130,
  'expansion_1_k': 5.2e-05,
  'tg_c': 86,
  't_max_c': 70,
  'moisture_absorption_pct': 0.1,
  'heat_sensitivity': 0.84}]

DEFAULT_USERS = [
    {"username": "admin", "employee_name": "Администратор", "role": "admin", "password": "admin123"},
    {"username": "technolog", "employee_name": "Технолог", "role": "technologist", "password": "tech123"},
]

IMPREGNATIONS = [
    {
        "kod": "TEST_HARD_01",
        "name": "Тестовая упрочняющая пропитка 1",
        "base_type": "полимерная",
        "composition": "УФ-отверждаемое акрилатно-полисилоксановое связующее, реактивный разбавитель, фотоинициатор",
        "purpose": "упрочняющее покрытие для органических офтальмологических линз",
        "stage_group": "упрочняющее",
        "is_final_layer": False,
        "external_only": False,
        "application_method": "центрифугирование",
        "viscosity_mpa_s": 23,
        "surface_tension_mn_m": 32,
        "evaporation_rate": 0.46,
        "thermal_stability_c": 92,
        "target_layer_thickness_um": 7.0,
        "initial_solvent_pct": 22,
        "overheat_sensitivity": 0.52,
        "requires_uv": True,
    },
    {
        "kod": "TEST_HARD_02",
        "name": "Тестовая упрочняющая пропитка 2",
        "base_type": "полимерная",
        "composition": "УФ-отверждаемая акрилатная смола, безводный реактивный разбавитель, фотоинициатор",
        "purpose": "тонкое упрочняющее покрытие для пластиковых оптических изделий",
        "stage_group": "упрочняющее",
        "is_final_layer": False,
        "external_only": False,
        "application_method": "центрифугирование",
        "viscosity_mpa_s": 18,
        "surface_tension_mn_m": 31,
        "evaporation_rate": 0.58,
        "thermal_stability_c": 90,
        "target_layer_thickness_um": 4.2,
        "initial_solvent_pct": 15,
        "overheat_sensitivity": 0.50,
        "requires_uv": True,
    },
    {
        "kod": "TEST_HARD_03",
        "name": "Тестовая упрочняющая пропитка 3",
        "base_type": "водная",
        "composition": "Водная дисперсия акрил-уретанового полимера, сшивающая добавка, стабилизатор смачивания",
        "purpose": "тестовый водный вариант упрочняющего слоя для проверки расчетов",
        "stage_group": "упрочняющее",
        "is_final_layer": False,
        "external_only": False,
        "application_method": "погружение",
        "viscosity_mpa_s": 34,
        "surface_tension_mn_m": 38,
        "evaporation_rate": 0.32,
        "thermal_stability_c": 82,
        "target_layer_thickness_um": 5.8,
        "initial_solvent_pct": 54,
        "overheat_sensitivity": 0.58,
        "requires_uv": False,
    },
    {
        "kod": "TEST_HARD_04",
        "name": "Тестовая упрочняющая пропитка 4",
        "base_type": "спиртовая",
        "composition": "Изопропанольный раствор силоксан-акрилатного связующего, промотор адгезии",
        "purpose": "тестовый спиртовой вариант упрочняющего слоя для проверки расчетов",
        "stage_group": "упрочняющее",
        "is_final_layer": False,
        "external_only": False,
        "application_method": "распыление",
        "viscosity_mpa_s": 17,
        "surface_tension_mn_m": 25,
        "evaporation_rate": 0.74,
        "thermal_stability_c": 86,
        "target_layer_thickness_um": 3.1,
        "initial_solvent_pct": 63,
        "overheat_sensitivity": 0.47,
        "requires_uv": False,
    },
    {
        "kod": "TEST_AR_01",
        "name": "Тестовая антибликовая пропитка 1",
        "base_type": "спиртовая",
        "composition": "Этанольно-изопропанольный раствор низкоиндексного золь-гель связующего",
        "purpose": "тестовый антибликовый слой на спиртовой основе",
        "stage_group": "антибликовое",
        "is_final_layer": False,
        "external_only": False,
        "application_method": "погружение",
        "viscosity_mpa_s": 9,
        "surface_tension_mn_m": 23,
        "evaporation_rate": 0.82,
        "thermal_stability_c": 96,
        "target_layer_thickness_um": 0.42,
        "initial_solvent_pct": 78,
        "overheat_sensitivity": 0.32,
        "requires_uv": False,
    },
    {
        "kod": "TEST_AR_02",
        "name": "Тестовая антибликовая пропитка 2",
        "base_type": "полимерная",
        "composition": "УФ-отверждаемая низкоиндексная акрилатная смола, фотоинициатор, регулятор смачивания",
        "purpose": "тестовый антибликовый слой на полимерной основе",
        "stage_group": "антибликовое",
        "is_final_layer": False,
        "external_only": False,
        "application_method": "центрифугирование",
        "viscosity_mpa_s": 21,
        "surface_tension_mn_m": 29,
        "evaporation_rate": 0.55,
        "thermal_stability_c": 88,
        "target_layer_thickness_um": 0.65,
        "initial_solvent_pct": 28,
        "overheat_sensitivity": 0.42,
        "requires_uv": True,
    },
    {
        "kod": "TEST_AR_03",
        "name": "Тестовая антибликовая пропитка 3",
        "base_type": "комбинированная",
        "composition": "Спиртовая смесь с полимерным связующим и регулятором показателя преломления",
        "purpose": "тестовый антибликовый слой на комбинированной основе",
        "stage_group": "антибликовое",
        "is_final_layer": False,
        "external_only": False,
        "application_method": "распыление",
        "viscosity_mpa_s": 14,
        "surface_tension_mn_m": 30,
        "evaporation_rate": 0.62,
        "thermal_stability_c": 92,
        "target_layer_thickness_um": 0.58,
        "initial_solvent_pct": 46,
        "overheat_sensitivity": 0.38,
        "requires_uv": False,
    },
    {
        "kod": "TEST_AS_01",
        "name": "Тестовая антистатическая пропитка 1",
        "base_type": "водная",
        "composition": "Водная двухкомпонентная система проводящего полимерного комплекса, добавка и связующая смола",
        "purpose": "прозрачное антистатическое покрытие на основе проводящего полимера",
        "stage_group": "антистатическое",
        "is_final_layer": False,
        "external_only": True,
        "application_method": "распыление",
        "viscosity_mpa_s": 26,
        "surface_tension_mn_m": 35,
        "evaporation_rate": 0.42,
        "thermal_stability_c": 105,
        "target_layer_thickness_um": 0.35,
        "initial_solvent_pct": 55,
        "overheat_sensitivity": 0.48,
        "requires_uv": False,
    },
    {
        "kod": "TEST_AS_02",
        "name": "Тестовая антистатическая пропитка 2",
        "base_type": "водная",
        "composition": "Водная двухкомпонентная система проводящего полимерного комплекса для прозрачных проводящих покрытий",
        "purpose": "прозрачное антистатическое покрытие с низким поверхностным сопротивлением",
        "stage_group": "антистатическое",
        "is_final_layer": False,
        "external_only": True,
        "application_method": "погружение",
        "viscosity_mpa_s": 22,
        "surface_tension_mn_m": 35,
        "evaporation_rate": 0.40,
        "thermal_stability_c": 110,
        "target_layer_thickness_um": 0.30,
        "initial_solvent_pct": 58,
        "overheat_sensitivity": 0.46,
        "requires_uv": False,
    },
    {
        "kod": "TEST_AS_03",
        "name": "Тестовая антистатическая пропитка 3",
        "base_type": "спиртовая",
        "composition": "Изопропанольный раствор антистатической добавки и тонкопленочного связующего",
        "purpose": "тестовый антистатический слой на спиртовой основе",
        "stage_group": "антистатическое",
        "is_final_layer": False,
        "external_only": True,
        "application_method": "распыление",
        "viscosity_mpa_s": 13,
        "surface_tension_mn_m": 24,
        "evaporation_rate": 0.78,
        "thermal_stability_c": 86,
        "target_layer_thickness_um": 0.22,
        "initial_solvent_pct": 70,
        "overheat_sensitivity": 0.44,
        "requires_uv": False,
    },
    {
        "kod": "TEST_AS_04",
        "name": "Тестовая антистатическая пропитка 4",
        "base_type": "комбинированная",
        "composition": "Водная смесь с полимерным связующим и антистатической добавкой",
        "purpose": "тестовый антистатический слой на комбинированной основе",
        "stage_group": "антистатическое",
        "is_final_layer": False,
        "external_only": True,
        "application_method": "погружение",
        "viscosity_mpa_s": 24,
        "surface_tension_mn_m": 32,
        "evaporation_rate": 0.52,
        "thermal_stability_c": 92,
        "target_layer_thickness_um": 0.45,
        "initial_solvent_pct": 48,
        "overheat_sensitivity": 0.50,
        "requires_uv": False,
    },
    {
        "kod": "TEST_HYDRO_01",
        "name": "Тестовая гидрофобная пропитка 1",
        "base_type": "комбинированная",
        "composition": "Полимерное связующее, нанокомпоненты, органический растворитель",
        "purpose": "супергидрофобное покрытие для пластика, стекла и металлов",
        "stage_group": "гидрофобное",
        "is_final_layer": False,
        "external_only": True,
        "application_method": "распыление",
        "viscosity_mpa_s": 21,
        "surface_tension_mn_m": 24,
        "evaporation_rate": 0.52,
        "thermal_stability_c": 85,
        "target_layer_thickness_um": 5.0,
        "initial_solvent_pct": 38,
        "overheat_sensitivity": 0.45,
        "requires_uv": False,
    },
    {
        "kod": "TEST_HYDRO_02",
        "name": "Тестовая гидрофобная пропитка 2",
        "base_type": "фторсодержащая",
        "composition": "Фторсодержащий органосилановый поверхностный модификатор в органическом растворителе",
        "purpose": "гидрофобное и грязеотталкивающее покрытие для оптических поверхностей",
        "stage_group": "гидрофобное",
        "is_final_layer": False,
        "external_only": True,
        "application_method": "распыление",
        "viscosity_mpa_s": 12,
        "surface_tension_mn_m": 19,
        "evaporation_rate": 0.74,
        "thermal_stability_c": 76,
        "target_layer_thickness_um": 0.08,
        "initial_solvent_pct": 44,
        "overheat_sensitivity": 0.40,
        "requires_uv": False,
    },
    {
        "kod": "TEST_HYDRO_03",
        "name": "Тестовая гидрофобная пропитка 3",
        "base_type": "водная",
        "composition": "Водная эмульсия гидрофобизирующего полимера и сшивающей добавки",
        "purpose": "тестовый гидрофобный слой на водной основе",
        "stage_group": "гидрофобное",
        "is_final_layer": False,
        "external_only": True,
        "application_method": "погружение",
        "viscosity_mpa_s": 29,
        "surface_tension_mn_m": 34,
        "evaporation_rate": 0.36,
        "thermal_stability_c": 80,
        "target_layer_thickness_um": 0.9,
        "initial_solvent_pct": 56,
        "overheat_sensitivity": 0.52,
        "requires_uv": False,
    },
    {
        "kod": "TEST_OLEO_01",
        "name": "Тестовая олеофобная пропитка 1",
        "base_type": "фторсодержащая",
        "composition": "Фторсодержащий репеллентный компонент, гидрокарбон/фторрастворитель",
        "purpose": "олеофобное и гидрофобное нанослойное покрытие",
        "stage_group": "олеофобное",
        "is_final_layer": False,
        "external_only": True,
        "application_method": "распыление",
        "viscosity_mpa_s": 2,
        "surface_tension_mn_m": 18,
        "evaporation_rate": 0.86,
        "thermal_stability_c": 95,
        "target_layer_thickness_um": 0.20,
        "initial_solvent_pct": 88,
        "overheat_sensitivity": 0.34,
        "requires_uv": False,
    },
    {
        "kod": "TEST_OLEO_02",
        "name": "Тестовая олеофобная пропитка 2",
        "base_type": "фторсодержащая",
        "composition": "Фторполимер на основе перфторполиэфира с функциональными группами для связывания с поверхностью",
        "purpose": "антисмазывающее и олеофобное прозрачное покрытие для линз и стекла",
        "stage_group": "олеофобное",
        "is_final_layer": False,
        "external_only": True,
        "application_method": "погружение",
        "viscosity_mpa_s": 8,
        "surface_tension_mn_m": 17,
        "evaporation_rate": 0.80,
        "thermal_stability_c": 100,
        "target_layer_thickness_um": 0.10,
        "initial_solvent_pct": 82,
        "overheat_sensitivity": 0.36,
        "requires_uv": False,
    },
    {
        "kod": "TEST_OLEO_03",
        "name": "Тестовая олеофобная пропитка 3",
        "base_type": "комбинированная",
        "composition": "Спиртовая смесь с фторсодержащим поверхностным модификатором и органосилановым промотором адгезии",
        "purpose": "тестовый олеофобный слой на комбинированной основе",
        "stage_group": "олеофобное",
        "is_final_layer": False,
        "external_only": True,
        "application_method": "распыление",
        "viscosity_mpa_s": 14,
        "surface_tension_mn_m": 20,
        "evaporation_rate": 0.68,
        "thermal_stability_c": 84,
        "target_layer_thickness_um": 0.18,
        "initial_solvent_pct": 62,
        "overheat_sensitivity": 0.44,
        "requires_uv": False,
    },
    {
        "kod": "TEST_AF_01",
        "name": "Тестовая антизапотевающая пропитка 1",
        "base_type": "комбинированная",
        "composition": "Водно-гликолевая двухкомпонентная система, смачивающая добавка",
        "purpose": "постоянное прозрачное антизапотевающее покрытие",
        "stage_group": "антизапотевающее",
        "is_final_layer": False,
        "external_only": True,
        "application_method": "погружение",
        "viscosity_mpa_s": 32,
        "surface_tension_mn_m": 38,
        "evaporation_rate": 0.34,
        "thermal_stability_c": 120,
        "target_layer_thickness_um": 6.0,
        "initial_solvent_pct": 53,
        "overheat_sensitivity": 0.64,
        "requires_uv": False,
    },
    {
        "kod": "TEST_AF_02",
        "name": "Тестовая антизапотевающая пропитка 2",
        "base_type": "полимерная",
        "composition": "УФ-отверждаемое полимерное антизапотевающее покрытие, смачивающая добавка",
        "purpose": "прозрачное антизапотевающее покрытие для поликарбоната, ПММА, ПЭТ и оптически прозрачных термопластов",
        "stage_group": "антизапотевающее",
        "is_final_layer": False,
        "external_only": True,
        "application_method": "центрифугирование",
        "viscosity_mpa_s": 36,
        "surface_tension_mn_m": 35,
        "evaporation_rate": 0.48,
        "thermal_stability_c": 100,
        "target_layer_thickness_um": 6.5,
        "initial_solvent_pct": 38,
        "overheat_sensitivity": 0.60,
        "requires_uv": True,
    },
    {
        "kod": "TEST_AF_03",
        "name": "Тестовая антизапотевающая пропитка 3",
        "base_type": "водная",
        "composition": "Водный раствор полимера, сшиватель, смачивающая добавка",
        "purpose": "тестовый антизапотевающий слой на водной основе",
        "stage_group": "антизапотевающее",
        "is_final_layer": False,
        "external_only": True,
        "application_method": "распыление",
        "viscosity_mpa_s": 27,
        "surface_tension_mn_m": 39,
        "evaporation_rate": 0.30,
        "thermal_stability_c": 78,
        "target_layer_thickness_um": 2.0,
        "initial_solvent_pct": 66,
        "overheat_sensitivity": 0.62,
        "requires_uv": False,
    },
    {
        "kod": "TEST_PHOTO_01",
        "name": "Тестовая фотохромная пропитка 1",
        "base_type": "полимерная",
        "composition": "Фотохромная полимерная матрица, фотохромные красители серого спектра, акрилатное связующее",
        "purpose": "фотохромное покрытие серого оттенка для центрифугирования на офтальмологических линзах",
        "stage_group": "фотохромное",
        "is_final_layer": False,
        "external_only": False,
        "application_method": "центрифугирование",
        "viscosity_mpa_s": 70,
        "surface_tension_mn_m": 31,
        "evaporation_rate": 0.42,
        "thermal_stability_c": 76,
        "target_layer_thickness_um": 3.2,
        "initial_solvent_pct": 30,
        "overheat_sensitivity": 0.62,
        "requires_uv": True,
    },
    {
        "kod": "TEST_PHOTO_02",
        "name": "Тестовая фотохромная пропитка 2",
        "base_type": "полимерная",
        "composition": "Фотохромная полимерная матрица, фотохромные красители коричневого спектра, акрилатное связующее",
        "purpose": "фотохромное покрытие коричневого оттенка для центрифугирования на офтальмологических линзах",
        "stage_group": "фотохромное",
        "is_final_layer": False,
        "external_only": False,
        "application_method": "центрифугирование",
        "viscosity_mpa_s": 74,
        "surface_tension_mn_m": 31,
        "evaporation_rate": 0.40,
        "thermal_stability_c": 75,
        "target_layer_thickness_um": 3.4,
        "initial_solvent_pct": 31,
        "overheat_sensitivity": 0.64,
        "requires_uv": True,
    },
    {
        "kod": "TEST_PHOTO_03",
        "name": "Тестовая фотохромная пропитка 3",
        "base_type": "спиртовая",
        "composition": "Спиртовой раствор фотохромной добавки и тонкопленочного связующего",
        "purpose": "тестовый фотохромный слой на спиртовой основе",
        "stage_group": "фотохромное",
        "is_final_layer": False,
        "external_only": False,
        "application_method": "распыление",
        "viscosity_mpa_s": 24,
        "surface_tension_mn_m": 25,
        "evaporation_rate": 0.76,
        "thermal_stability_c": 72,
        "target_layer_thickness_um": 2.2,
        "initial_solvent_pct": 68,
        "overheat_sensitivity": 0.58,
        "requires_uv": False,
    },
]


def seed_reference_data():
    init_db()
    session = SessionLocal()
    try:
        existing_materials = {item.kod: item for item in session.query(Material).all()}
        for row in MATERIALS:
            item = existing_materials.get(row["kod"])
            if item is None:
                session.add(Material(**row))
            else:
                for key, value in row.items():
                    setattr(item, key, value)
        existing_impregnations = {item.kod: item for item in session.query(Impregnation).all()}
        desired_codes = {row["kod"] for row in IMPREGNATIONS}
        for item in session.query(Impregnation).all():
            if item.kod not in desired_codes:
                session.delete(item)
        session.flush()
        existing_impregnations = {item.kod: item for item in session.query(Impregnation).all()}
        for row in IMPREGNATIONS:
            item = existing_impregnations.get(row["kod"])
            if item is None:
                session.add(Impregnation(**row))
            else:
                for key, value in row.items():
                    setattr(item, key, value)
        if session.query(User).count() == 0:
            for row in DEFAULT_USERS:
                session.add(User(
                    username=row["username"],
                    employee_name=row["employee_name"],
                    role=row["role"],
                    password_hash=generate_password_hash(row["password"]),
                    is_active=True,
                ))
        session.commit()
    finally:
        session.close()


if __name__ == "__main__":
    seed_reference_data()
    print("Справочники заполнены")
